Handle import scope dependencies in dependencyManagement (multiple goals)
mojohaus/versions pull request #476
Opened 2021-08-02 09:57 UTC by frode-carlsen

Fixes #346, #395 for following goals
* use-dep-version
* use-latest-versions
* use-latest-snapshots
* use-latest-release
* use-next-releases
* use-next-versions
* use-next-snapshots

2021-09-07 13:20 UTC, mfriedenhagen requested changes
Hi @frode-carlson, 

first of all, thanks for this contribution. 
I have added remarks about formatting and it looks like you introduced tabs at a few places if I am not mistaken (before comment `// handle normally declared dependencies`). And the blank lines before `// handle import dependencies specially`
It would be mighty helpful if you included an invoker test as well which checks at least some of your changes.

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
> +                useNextVersions( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
                useNextVersions( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
> +                useNextSnapshots( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
                useNextSnapshots( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
> +            useNextReleases( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
            useNextReleases( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
> +                    useLatestVersions( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
                    useLatestVersions( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
> +                useLatestSnapshots( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
                useLatestSnapshots( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
> +                useLatestReleases( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
                useLatestReleases( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-07 13:20 UTC, mfriedenhagen commented on src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
> +                useDepVersion( pom, PomHelper.readImportedPOMsFromDependencyManagementSection(pom) );
```suggestion
                // handle normally declared dependencies
                useDepVersion( pom, getProject().getDependencyManagement().getDependencies() );

                // handle import dependencies specially
                useDepVersion( pom, PomHelper.readImportedPOMsFromDependencyManagementSection( pom ) );
```

2021-09-10 07:41 UTC, frode-carlsen commented
added test case and applied fixes for tabs

2021-09-16 05:07 UTC, frode-carlsen commented
@mfriedenhagen added test case and applied fixes for tabs

2022-04-14 06:31 UTC, nicktindall commented
This would be really handy

2022-11-12 10:11 UTC, adpriebe commented
Is there any chance of this PR getting merged? The documentation is very clear that the `dependencyManagement` section is processed by default, and therefore it is surprising that something like `mvn versions:use-latest-releases` does not also update import scoped dependencies in `dependencyManagement` to the latest release versions.

2022-11-12 10:39 UTC, ajarmoniuk commented
It doesn't? Yesterday I checked it and it did update those. I did check that with maven 3.2.5 as well as 3.6.3.

Could you please share a test scenario where it doesn't update those dependencies? By that I understand a test pom.xml, not just a maven command line.

2022-11-12 12:25 UTC, adpriebe commented
Hi @ajarmoniuk thanks for your fast response! Here is a contrived `pom.xml` that reproduces the issue:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>2.7.0</version> <!-- old version -->
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
```

I have tested the above with both Maven 3.6.0 and 3.8.6 using command `mvn versions:use-latest-release -Dincludes=org.springframework.boot:spring-boot-dependencies`. The command succeeds without updating anything.

I would also note that the following `pom.xml` and command `mvn versions:update-properties -Dincludes=org.springframework.boot:spring-boot-dependencies` works as expected, with the `spring.version` property being updated:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
                <spring.version>2.7.0</spring.version> <!-- old version -->
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
```

2022-11-13 09:06 UTC, ajarmoniuk commented
Indeed, I was able to reproduce the issue using your POMs. Thank you. I will now update all mojos to include the fix for this issue.

2022-11-13 11:31 UTC, ajarmoniuk commented
For some reason, I wasn't able to create a test using a bom in the `it-repo` repository, even if I copied the Spring Boot BOM there. Neither did using `org.codehaus.mojo:mojo-parent` reproduce the problem. In both cases, the BOM was present in `project.dependencyManagement.dependencies`.

2023-12-14 02:05 UTC, closed without merging