Enhancement: add allowDowngrade capability to UseLatestReleasesMojo, UseNextReleasesMojo, UseNextVersionsMojo
mojohaus/versions pull request #883
Opened 2022-12-27 09:20 UTC by ajarmoniuk

The three mojos in the summary did not have the "allowDowngrade" capability. Adding it for consistence.

2022-12-27 09:21 UTC, ajarmoniuk commented
@slawekjaranowski please review

2023-01-04 20:20 UTC, slawekjaranowski requested changes

2023-01-04 20:20 UTC, slawekjaranowski commented on versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
> +     * @since 2.12.0
2.15.0

2023-01-04 20:20 UTC, slawekjaranowski commented on versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
> +     * @since 2.12.0
2.1.5.0

2023-01-06 16:12 UTC, slawekjaranowski approved these changes

2023-01-06 16:12 UTC, merged