Resolves #550: New parameter to DisplayPluginUpdatesMojo: processUnboundPlugins
mojohaus/versions pull request #886
Opened 2022-12-29 21:02 UTC by ajarmoniuk

- if true, will show updates to plugins defined in parent poms, which have no version in the current pom
- false by default to retain backwards compatibility

@slawekjaranowski please review

2023-01-01 20:17 UTC, slachiewicz approved these changes

2023-01-04 20:53 UTC, slawekjaranowski requested changes

2023-01-04 20:53 UTC, slawekjaranowski commented on versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/invoker.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
New file please use standard header

2023-01-04 20:53 UTC, slawekjaranowski commented on versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/parent.xml
> +  ~ Licensed to the Apache Software Foundation (ASF) under one
New file please use standard header

2023-01-04 20:53 UTC, slawekjaranowski commented on versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/parent.xml
> +  </prerequisites>
Should be used only for maven-plugin packaging

2023-01-04 20:53 UTC, slawekjaranowski commented on versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/verify.groovy
> + * Licensed to the Apache Software Foundation (ASF) under one
not asf

2023-01-04 22:59 UTC, slawekjaranowski approved these changes

2023-01-04 22:59 UTC, merged