Issue #74: Add display-extension-updates
mojohaus/versions pull request #908
Opened 2023-01-24 21:47 UTC by ajarmoniuk

First stage of extensions support.

*Not* supporting core extensions. Only build extensions are supported.

@slawekjaranowski please review

2023-01-25 17:25 UTC, slawekjaranowski reviewed
Extension can also by defined in `.mvn/extensions.xml`
https://maven.apache.org/configure.html#mvn-extensions-xml-file

2023-01-25 17:25 UTC, slawekjaranowski commented on versions-common/src/main/java/org/codehaus/mojo/versions/utils/ExtensionBuilder.java
> + * Licensed to the Apache Software Foundation (ASF) under one
It is not ASF project

2023-01-25 19:47 UTC, ajarmoniuk commented
@slawekjaranowski added support for core extensions declared in `.mvn/extensions`

2023-02-01 19:02 UTC, slawekjaranowski requested changes

2023-02-01 19:02 UTC, slawekjaranowski commented on versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
> + * <b>Does not check the core extensions.</b>
Is it true?

2023-02-12 23:42 UTC, slawekjaranowski commented on versions-model-core-extensions/src/main/mdo/core-extensions.mdo
> +  xsi:schemaLocation="http://codehaus-plexus.github.io/MODELLO/1.4.0 http://codehaus-plexus.github.io/modello/xsd/modello-1.4.0.xsd"
There is 2.0.0 version of modelo xsd
https://codehaus-plexus.github.io/modello/modello.html

2023-02-12 23:42 UTC, slawekjaranowski commented on versions-maven-plugin/src/it/it-display-extension-updates-004/child/.mvn/extensions.xml
> +            xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
Core extensions can be defined only in project root - in child module it will be skipped as I know.

2023-02-12 23:42 UTC, slawekjaranowski commented on versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
> +@Mojo(name = "display-extension-updates", threadSafe = true)
Maybe we should use `aggregator` for such mojo
core extensions can be defined only in project root.

2023-02-16 19:37 UTC, slawekjaranowski commented
@ajarmoniuk please rebase this PR ... now I see in diff changes from master ...

2023-02-16 19:58 UTC, ajarmoniuk commented
> @ajarmoniuk please rebase this PR ... now I see in diff changes from master ...

Rebased.

2023-02-18 19:11 UTC, slawekjaranowski requested changes
Ok, I see 
you create new module `versions-model-core-extensions` with contain a copy file core-extensions.mdo from Maven core.

I think that better will be use `org.apache.maven.cli.internal.extension.model.io.xpp3.CoreExtensionsXpp3Reader` even it is internal

2023-02-18 19:11 UTC, slawekjaranowski commented on versions-maven-plugin/src/it/it-display-extension-updates-004/child/.mvn/extensions.xml
> +            xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
I don't see a check for `dummy-impl` so why this file exists?

2023-02-18 19:19 UTC, ajarmoniuk commented
> Ok, I see you create new module `versions-model-core-extensions` with contain a copy file core-extensions.mdo from Maven core.
> 
> I think that better will be use `org.apache.maven.cli.internal.extension.model.io.xpp3.CoreExtensionsXpp3Reader` even it is internal

Are you sure?

I asked you before when you requested me to change that:

>     Ok, so I have a question about this. Maybe I could appeal to the Maven project to make this public, or at least export the mdo?

>     I could also include the mdo file in the versions plugin. But what about its license then? > It's the ASF -- should we keep it as ASF then?

>     As an alternative, I could create a parser from scratch, be it manually, or using a bespoke XSD file and generate a parser from it.

> So, what do you think should be the course of action here?

So, what should it be?

2023-02-18 19:21 UTC, ajarmoniuk commented
> I don't see a check for dummy-impl so why this file exists?

to test if the .mvn/extensions is *not* processed in the child.

2023-02-18 19:45 UTC, ajarmoniuk commented
@slawekjaranowski and if you need time to decide, feel free to remove this from the upcoming release. 

It's not so easy. 

Maven Embedder 3.2.5 does not have Core Extensions parser. Only 3.3.9 and later has it. So we cannot use the one from Maven (so, it can't be _provided_).

2023-02-19 09:44 UTC, slawekjaranowski commented
> @slawekjaranowski and if you need time to decide, feel free to remove this from the upcoming release.
> 
> It's not so easy.
> 
> Maven Embedder 3.2.5 does not have the Core Extensions parser. Only 3.3.9 and later has it. So we cannot use the one from the same version as Maven.
> 
> https://maven.apache.org/ref/3.2.5/maven-embedder/xref/index.html

Ok, I must review of it more carefully ... so I will do it again in next week

Maybe some one else want to look also - @slachiewicz ?

2023-02-19 10:04 UTC, ajarmoniuk commented
@slawekjaranowski @slachiewicz 

It's not the only case like this in this plugin. Please have a look at e.g. parsing raw pom. Currently it's an ad-hoc parser created from scratch in the plugin, but it actually depends on Maven and the underlying document, which is **owned** by the Maven project. So it's a very similar case.

2023-02-27 20:14 UTC, ajarmoniuk commented
@slawekjaranowski I propose that we keep a version of this PR with the file from the Apache Maven project with its own ASF license and its own Modello version. Until there comes an API from Maven, which we can request or implement.

2023-02-28 16:52 UTC, slawekjaranowski reviewed
I think that we not need new module only for a few classes, we not need xsd for it, it is only for internal purpose.

I would like to put core-extensions.mdo into versions-common where is only used.

2023-02-28 16:52 UTC, slawekjaranowski commented on versions-model-core-extensions/pom.xml
> +              <goal>xdoc</goal>
We should not generate xsd for this model - it is internally used for reading extensions.xml

2023-02-28 17:14 UTC, ajarmoniuk commented
> I think that we not need new module only for a few classes, we not need xsd for it, it is only for internal purpose.
> 
> I would like to put core-extensions.mdo into versions-common where is only used.

Applied.

2023-02-28 17:48 UTC, ajarmoniuk commented
> I think that we not need new module only for a few classes, we not need xsd for it, it is only for internal purpose.
> 
> I would like to put core-extensions.mdo into versions-common where is only used.

Oh yes, I remember it now. The reason why I created that module was that I couldn't go around javadoc generation errors -- classes were generated.

2023-04-17 07:00 UTC, ajarmoniuk commented
@slawekjaranowski is there anything else to be done about this PR?

2023-05-09 20:38 UTC, slawekjaranowski commented
Hi,
I was removed `maven-embedder` from dependency - we have a copy
I restored license header in files with longer history - we don't know why such license was used ... 

Wait for build and we can go.

2023-05-09 21:10 UTC, merged